
spring:
  h2:
    console.enabled: true

  datasource:
    url: jdbc:h2:mem:diet
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
